version: '3'

services:
  mysql:
    container_name: mysql
    platform: linux/x86_64
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taxonomy
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - mysql-network
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  mysql-network:
    external:
      name: mysql-network
